### PR TITLE
added search functionality

### LINKED ISSUE #8: Add Search Functionality + Components
## Issue

Currently we are not showing any search feature set inside of the example project, and would love to add this and show more information around using this inside of this location and leveraging metadata to improve search results.

This issue is a bit more challenging since the documentation has not been released yet but would be a great candidate for someone getting familiar with the repo and wanting to dive directly into the SDK logic.

## Solution 

- [ ] Learn and understand how to properly pass parameters to the search endpoint 
- [ ] Add a text input and button to manage searching a specific string 
- [ ] show the results that come back from the search endpoint

### PR DESCRIPTION
**Pull request by derajohnson**
This PR fixes #8 

added search functionality
added input field and search button

### CODE REVIEW

**Comment by derajohnson** [comment]
@jordan-pieces Please review. I wanted to add you as a reviewer but i couldn't.

**Comment by jordan-pieces** [comment]
will review this soon and let you know how its looking - thanks for opening this up 👍

**Comment by jordan-pieces** [comment]
will be working on merging this with the new UI updates following a response from pythonistical on PR #35

**Comment by jordan-pieces** [comment]
@derajohnson totally my fault, but i missed this PR and it has already started to fall out of date, and i wanted to check in with you and see if you would be willing to follow along with a little step by step process here that i could write up for you on how to use this SDK endpoint properly, and then you can try to implement it on your own branch and open a new PR. 

Let me know how that sounds 👍

**Comment by derajohnson** [comment]
sure thing

**Comment by jordan-pieces** [comment]
alright @derajohnson we will get a document created for you around the search endpoint and open up a new issue with the details, and i can assign it to you. 👍

**Pull request closed without merging**
