### PR TITLE
added ts and react

### LINKED ISSUE #32: Add typescript and react in the package.json dependencies
The current configuration lacks TypeScript and React in the package.json dependencies, which results in failures during GitHub Actions runs.  we need to add TypeScript and React to the project dependencies in the package.json file.

### PR DESCRIPTION
**Pull request by derajohnson**
This PR fixes #32

Moved `@types/node`, `@types/react`, `@types/react-dom` to dev dependencies and installed `react`

### CODE REVIEW

**Comment by shivay-at-pieces** [comment]
Thanks @derajohnson can you also add TypeScript as a dependency.

**Comment by derajohnson** [comment]
done @shivay-at-pieces

**Comment by shivay-at-pieces** [comment]
looks good to me. @jordan-pieces if you want to also just have a quick review for this one

**Review by shivay-at-pieces — APPROVED** [review]

**Review by jordan-pieces — APPROVED** [review]
looks great ! good work getting these added

**Comment by jordan-pieces** [comment]
> looks good to me. @jordan-pieces if you want to also just have a quick review for this one

go ahead and merge whenever @shivay-at-pieces

**Pull request merged**
