### PR TITLE
Create build-test.yml

### PR DESCRIPTION
**Pull request by RohanMishra315**
Created the build-test.yml file.

**Description**

This PR fixes # 31

### CODE REVIEW

**Review by shivay-at-pieces — COMMENTED** [review]
Works fine. Do you mind sharing the motivation behind adding: 
```
    - name: Create test directory
        run: mkdir test

      - name: Create test file
        run: echo "This is a test" > test/test.js
```
@RohanMishra315

**Comment by RohanMishra315** [comment]
Hey @shivay-at-pieces It was a task to add in build-test.yml file  given by @jordan-pieces . Here 
Screenshot 2023-12-20 201403

**Comment by shivay-at-pieces** [comment]
Cool :)

**Review by shivay-at-pieces — APPROVED** [review]

**Comment by shivay-at-pieces** [comment]
cc @jordan-pieces you can have a look if we can merge this.

**Comment by jordan-pieces** [comment]
can merge this but want to add in another test to have as an example for others created tests and how we can add all of the examples here. @shivay-at-pieces should go in today

**Review by jordan-pieces — APPROVED** [review]
going to merge this and give it a go, will likely try to upgrade and run any endpoint in the test file that was created. if after testing this a few times it is not performing as intended it will be removed temporarily until improved! 💯

**Pull request merged**
