### PR TITLE
WIP: @pythonisticals UI Update PR Rework with Notes 

### LINKED ISSUE #3: Update UI and Add Improved Styling
The current UI in your browser is very light and goes beyond your available window space when loading the page. There are a few improvements that could be made here, but opening this up to others who would like to contribute.

There is not a particular direction laid out yet, but will create some rough sketches in a day or two to give everyone some time.

I will add any ideas in the comments that i have, but please add anything that seems like a good direction. Lets keep this conversation high level and focused on the UI of the application.

### PR DESCRIPTION
**Pull request by jordan-pieces**
## Description 
This PR fixes #3. blended in some of the changes with some other updates to the UI itself to prep for the new conversational copilot example coming soon! 

@pythonistical i wanted to say good initial work on the design and putting together some ideas around the homepage, but the specifics on how it was implemented needed to be ironed out a little bit further, along with handling some errors for rendering the view. I have been working on a Pieces Copilot example and am planning on merging all of this in together with a new view that will have that content, or further down the page. so i wanted to take some time to get into your work and leave you notes on the improvements and changes I made, and why I made them to help you as you are building your skills in react and moving out of a more pure html environment - which i could see in your work inside of the index.html file on your PR. 

Take some time to pull down this branch, review it and see if is up to par with some of the things that you were thinking, and how we can add some more of your personal touch.

A few things that I need help with if you would like before this can be merged: 

- [x] Font Color for the headers (create a new snippet, update snippet, etc) 
- [x] button styles pasted on to the other buttons on the main container 
- [ ] offline state for the "You're Connected Pill"
- [x] empty state suggestion text for all of the text boxes 
- [ ] toning down the "boldness" of the black and white colors, a little softer 
- [ ] reactivity improvements for different screen sizes

We will have to have another mini sprint on the card styles, and the copilot will be coming very soon too.

Let me know your thoughts :)

### CODE REVIEW

**Comment by pythonistical** [comment]
Yes, @jordan-pieces I would like to know what font colors you would like for the headers. And can you explain the second point in detail? For the third and sixth points, It will require interactivity and JS which I am not learning right now (I am learning Python), I would appreciate some support here. In the fourth point, I have coded empty slate suggestions, should I tone down their colors more? I have resolved the fifth point.

**Comment by jordan-pieces** [comment]
@pythonistical lets get the font color on the headers setup as white to match the others 

Point number 2:
- the styles on the button here: 
Screenshot 2023-12-14 at 1 50 21 PM

need to be applied to here the other buttons (copy and paste): 
Screenshot 2023-12-14 at 1 51 22 PM

- i can handle the interactivity sections here (3 + 6), and ill send over some notes on that just so you can read about it later 

- i will take care of the placeholders and getting them added and we can just go with the copy that you added.

Were you able to review my notes and build the branch locally to see the changes that have been made? 

Let me know once you review the notes in the code, i can take care of the rest of the tasks here as this will help support the copilot view as well.

**Comment by jordan-pieces** [comment]
here is the updated visual UI (minimal here): 
Screenshot 2023-12-14 at 3 38 31 PM

**Comment by jordan-pieces** [comment]
reactivity and offline state are both going to be held on for now, and we can curate two issues for those steps post this merge. @pythonistical let me know when you are able to take a look and from here we can get this merged in !

I will push a few changes for the color styles to make it a little easier on the eyes. 👍

**Comment by jordan-pieces** [comment]
Alright I am going to add notes following the updates on the branch and for @pythonistical here they are: 

- First this change to the indicator from @Pratere to help support when the indicator is not already attached to the dom:

Screenshot 2023-12-15 at 10 40 44 AM

- Second this update about your index.html work and why that code should not live there: 

Screenshot 2023-12-15 at 10 42 29 AM

- Third, the changes to the header to add a background and a little bit of styling and more:

Screenshot 2023-12-15 at 10 53 25 AM

- Fourth, working with the indicator component and adding an icon:
 
Screenshot 2023-12-15 at 10 53 42 AM

- Fifth , working with the containers and larger sections on homepage: 

Screenshot 2023-12-15 at 11 04 52 AM

- Sixth, adding a bit of reactivity on the delete button:

Screenshot 2023-12-15 at 11 05 31 AM

You can see all of this in this branch up above, and should cap off most of the changes that will take place for this section thus far. Let me know if you have any questions, and I would just use these notes as reference. In the future we can work closer on some more tightly scoped issues to make the focus a bit tighter. @pythonistical 

my goal is to merge this PR today

**Comment by jordan-pieces** [comment]
merging this in prep for work this week - expect more updates EOD monday and each day until the meetup on wednesday! :) 

large change to the layout and moving us towards a more expandable UI interface for the Copilot example!

**Pull request merged**
