### PR TITLE
Create Issue & PR templates

### PR DESCRIPTION
**Pull request by shivay-at-pieces**
Adding a few templates: 
- bug type
- feature request 
- blank template
- PR template

Fixes the comment in #15

### CODE REVIEW

**Comment by Sophyia7** [comment]
@shivay-at-pieces This is awesome! Let's wait for Jordan before merging.

**Comment by jordan-pieces** [comment]
would love to get a design template added here for any designers that are in the program that want to open up some visual based issues @shivay-at-pieces @Sophyia7

**Comment by Sophyia7** [comment]
@shivay-at-pieces if you haven't started this. I would like to work on the design template.

**Comment by shivay-at-pieces** [comment]
Sure if you wish to add to this @Sophyia7 go ahead.

**Review by jordan-pieces — APPROVED** [review]
awesome here @shivay-at-pieces we can make updates in the future as we find out what works for everyone contributing :)

**Comment by jordan-pieces** [comment]
@Sophyia7 lets get the design issue template added on a separate PR whenever you have time, I will create the issue and tag you on it

**Pull request merged**
