### PR TITLE
updated--example-ts--to--example-typescript

### PR DESCRIPTION
**Pull request by HarshitNagpal29**
**Description**

This PR fixes #

### CODE REVIEW

**Comment by HarshitNagpal29** [comment]
@jordan-pieces Sir i have updated the name from example-ts to example-typescript as mentioned in the issue https://github.com/pieces-app/example-ts/issues/47 sorry for not asking to get assigned as I found that issue to very small and therefore didn't consider the need to get assigned, apart from example-ts repo I have updated the name in other repos as well should I create pull request for them or not, will wait for you response.

**Review by jordan-pieces — APPROVED** [review]
wonderful - thank you for taking care of this. you are correct that this was a small issue but in the future I would be more than happy to get you assigned before starting on an issue, just in case there is someone already working on it. 

Regardless your contribution is very much appreciated 👍

**Comment by HarshitNagpal29** [comment]
@jordan-pieces Sir, again i am sorry from next time I will always ask to assign me issue first, Sir I have created PR in respective repos as I mentioned earlier, updating their files, please check once in different repos and please tell me if there is any issue regarding it , here are the links to those PRs:
https://github.com/pieces-app/awesome-pieces/pull/2
https://github.com/pieces-app/opensource/pull/29
https://github.com/pieces-app/pieces-os-client-sdk-for-typescript/pull/21

**Comment by jordan-pieces** [comment]
> @jordan-pieces Sir, again i am sorry from next time I will always ask to assign me issue first, Sir I have created PR in respective repos as I mentioned earlier, updating their files, please check once in different repos and please tell me if there is any issue regarding it , here are the links to those PRs: [pieces-app/awesome-pieces#2](https://github.com/pieces-app/awesome-pieces/pull/2) [pieces-app/opensource#29](https://github.com/pieces-app/opensource/pull/29) [pieces-app/pieces-os-client-sdk-for-typescript#21](https://github.com/pieces-app/pieces-os-client-sdk-for-typescript/pull/21)

These have been merged and the repo naming has been updated 👍 great work here @HarshitNagpal29 !

**Comment by HarshitNagpal29** [comment]
@jordan-pieces Thanks sir for your appreciation, also I want to thank you and your team as well because I have been using Pieces for the past two months and it has increased my productivity, I would love to contribute more and more, can you please suggest me some good first issues, mainly in js node js, or react, or maybe related, I can help in writing documentation as well as I am exploring the field of technical writing. Would love to contribute more.

**Pull request merged**
