### PR TITLE
Implement Timer to Hide "You're Connected" Text

### LINKED ISSUE #39: Implement Timer to Hide "You're Connected" Text
**Problem Statement:**
Upon connecting to the Pieces OS, there is a need to enhance the user experience by implementing a timer that automatically hides the **"You're Connected"** text and shrinks the button after a certain duration.

**Proposed Changes:**
1. Identify the element containing the "You're Connected" text and the associated button.
2. Implement a timer function in the relevant JavaScript file.
3. Upon connection, trigger the timer to start.
4. After the specified duration, hide the text and apply the button shrink effect.

Users will experience a more streamlined interface where the **"You're Connected"** text disappears, and the button shrinks after a set period, providing a cleaner visual feedback post-connection.

### PR DESCRIPTION
**Pull request by agrim0312**
**Description**
fixed #39
Upon connecting to the Pieces OS, there is a need to enhance the user experience by implementing a timer that automatically hides the "You're Connected" text and shrinks the button after a certain duration.

This PR fixes #
Identify the element containing the "You're Connected" text and the associated button.
Implement a timer function in the relevant JavaScript file.
Upon connection, trigger the timer to start.
After the specified duration, hide the text and apply the button shrink effect.

### CODE REVIEW

**Comment by agrim0312** [comment]
fixed #48 @jordan-pieces you can review my PR

**Review by shivay-at-pieces — COMMENTED** [review]
LGTM, only point is that the animation can be a bit more smoother.

**Comment by shivay-at-pieces** [comment]
cc @jordan-pieces

**Review by jordan-pieces — APPROVED** [review]
looks good @agrim0312 - @shivay-at-pieces your correct we can clean up the animation here but lets just get a related issue created to come back to this now that we have an initial implementation of it! 👍

**Pull request merged**
