### PR TITLE
Implement Button Functionality for Launching Pieces OS

### LINKED ISSUE #41: Implement Button Functionality for Launching Pieces OS
**Problem Statement:**
Currently, when Pieces OS is not connected, the UI lacks a functional aspect to initiate the connection. To improve user interaction, we want to add button functionality to the "**Not Connected**" button, allowing users to launch Pieces OS by clicking it.

**Expected Outcome:**
Users will be able to launch Pieces OS by clicking the **"Not Connected"** button, enhancing the user experience and providing a straightforward way to establish a connection.

### PR DESCRIPTION
**Pull request by agrim0312**
**Description**
Implement Button Functionality for Launching Pieces OS
This PR fixed #41
Problem Statement:
Currently, when Pieces OS is not connected, the UI lacks a functional aspect to initiate the connection. To improve user interaction, we want to add button functionality to the "Not Connected" button, allowing users to launch Pieces OS by clicking it.

Expected Outcome:
Users will be able to launch Pieces OS by clicking the "Not Connected" button, enhancing the user experience and providing a straightforward way to establish a connection.

### CODE REVIEW

**Review by shivay-at-pieces — COMMENTED** [review]
Hey @agrim0312 great work here. Do you mind also addressing the issue in #46 
At the moment, we don't have an error boundary for Pieces OS not running. So if we can also take care of that, it should prevent from the error popping up.

**Comment by agrim0312** [comment]
@shivay-at-pieces As error-boundary is used only for rendering error and these errors were overthrown by network error So I just created a div that will render when the piecesOS is not running in the background. I tested it in the build and it worked fine. I hope that this was the issue that you were refering to . If I missunderstood the issue please pardon me.
issue fixed #46
description - add an error boundary, and show in the project itself that Pieces OS isn't running in the background right now.
image

**Comment by shivay-at-pieces** [comment]
At the moment, it shows that you are connected to Pieces in the badge even though Pieces isn't running in the background. 
image

**Comment by agrim0312** [comment]
sure I'll fix it

**Comment by agrim0312** [comment]
@shivay-at-pieces Fixed the text. You can review it now.

**Comment by shivay-at-pieces** [comment]
Hey @agrim0312 there is still some work remaining on how we handle the button state when Pieces OS is connected and disconnected, as you can see in this video. You can see that the state of the button doesn't change. and we have to refresh to see the state change when Pieces OS is connected/disconnected 


https://github.com/pieces-app/example-ts/assets/143828586/3b4426ed-2412-4587-a663-d308201221e6

**Comment by agrim0312** [comment]
sure working on it

**Comment by agrim0312** [comment]
@shivay-at-pieces I used prop drilling method to  manage the state of button. I hope you were looking for this.

**Comment by jordan-pieces** [comment]
this is a much better improvement here and will at least get users up and running when they are not able to see snippets in the viewer, as well as with the new copilot chat. We we could potentially improve here by adding a loading state while a connection is being made that way we avoid ever hitting an error. @agrim0312 or @shivay-at-pieces if you want to get an issue created with details on an improvement and link it back to this pr that would be great!

**Review by jordan-pieces — APPROVED** [review]
looking good! be sure to get some general comments in a few more locations in future PRs 👍

**Comment by agrim0312** [comment]
sure :+1:  @jordan-pieces

**Pull request merged**
